[package]
name = "halloffame"
version = "0.1.0"
authors = ["Nikita Kuznetsov <n@8gen.team>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
hex = "0.4.3"
serde = "1"
serde_json = "1"
libsecp256k1 = "0.3.5"
near-contract-standards = "3.1.1"
